### ISSUE TITLE
pls don't use my regular secret-file lol

### ISSUE THREAD

**Issue by Powersource** [Kuska-ssb/solar#1]
Just tried this out and if I understand things correctly it:

* first reads my `~/.ssb/secret` file
* then publishes messages to `solar/feeds.db/db`

which is technically a fork (or not even a fork I guess, since it doesn't have any messages in common). It doesn't do any damage right now I think but I think it's kind of asking for an accident to happen in the future. I think that if a client is using `~/.ssb/secret` then it should only publish to `.ssb/flume/log.offset`, and if it publishes to `solar/feeds.db/db` then it should use something like `solar/secret`.

Sorry I just got freaked out for a second :|

**Comment by Powersource** [comment]
cc @adria0 

Really fun that the project is progressing to well btw :)

**Comment by adria0** [comment]
Oops! Yes, this makes a lot of sense.  A good option seems to use the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) so I will put all the stuff into `~/.local/share/solar`

**Comment by Powersource** [comment]
Ah yeah using xdg sounds like a good idea :)
